[package]
name = "maze"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
crossterm = "0.28.1"
rand = "0.8.5"

[profile.dev.package."*"]
opt-level = 3
